# docker compose -f docker-compose.production.yml up --build --force-recreate

version: '3'

services:
  app:
    image: docker-nextjs-production
    build:
      dockerfile: Dockerfile.production
    environment:
      - PORT=3000
    ports:
      - 3000:3000